Django_EShop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls", namespace="website")),
    path("shop/", include("shop.urls", namespace="shop")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import index, detail, store, checkout, add_to_cart, cart_detail, remove_from_cart

app_name = 'shop'

urlpatterns = [
    path("", index, name="index"),
    path("store", store, name="store"),
    path("checkout/", checkout, name="checkout"),
    path("<int:id>/<str:title>/", detail, name="detail"),
    path("add-to-cart/", add_to_cart, name="add_to_cart"),
    path("cart/", cart_detail, name="cart_detail"),
    path("cart/remove/<int:product_id>", remove_from_cart, name="remove_from_cart"),
]

website/urls.py
from django.urls import path
from .views import index
app_name = 'website'


urlpatterns = [
    path("", index, name="index"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class SoftUserManager(UserManager):

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class User(AbstractUser):
    mobile = models.CharField(max_length=11, unique=True)
    email = models.EmailField(_('email address'), unique=True)
    deleted = models.BooleanField(default=False, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    def delete(self, using=None, keep_parents=False):
        self.deleted = True
        self.save()

shop/models.py

from tkinter.constants import CASCADE
from typing import Any

from django.conf import settings
#from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q  # for or operation
from django.urls import reverse

from .utility import upload_file_with_date
# Create your models here.

class BaseModelManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(deleted = False)
        # return super().get_queryset().filter(Q(deleted = False) | Q(deleted = None)) # or operation

class BaseModel(models.Model):
    deleted = models.BooleanField(default=False, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = BaseModelManager()

    def delete(self, using=None, keep_parents=False):
        self.deleted = True
        self.save()

    class Meta:
        abstract = True



class Category(BaseModel):
    title = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.title


class Product(BaseModel):
    title = models.CharField(max_length=100)
    content = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits= 10)
    image = models.ImageField(upload_to=upload_file_with_date(base_dir="media_files", sub_dir="product_images"))
    quantity = models.PositiveIntegerField()
    status = models.BooleanField(default=True) 
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=None, null=True)

    def __str__(self) -> str:
        return self.title

    def get_fields(self):
        return [(field.name, getattr(self, field.name)) for field in self._meta.fields]

    def get_absolute_url(self):
        return reverse("shop:detail", kwargs={"id": self.id, "title": self.title})



class Cart(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    # def __str__(self) -> str:
    #     return self.user.__str__


class Order(BaseModel):
    total_price = models.DecimalField(decimal_places=2, max_digits= 10)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status =  models.BooleanField(null=True)


class OrderProduct(BaseModel):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(decimal_places=2, max_digits= 10)


class PaymentLog(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits= 10)
    user_id = models.PositiveIntegerField()
    order_id = models.PositiveIntegerField()
    status = models.CharField(max_length=100)
    error_code = models.CharField(max_length=200)


website/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.decorators.http import require_POST

from . import models
from .models import Product
from decimal import Decimal
from .cart import Cart

def checkout(request):
    return render(request, "checkout.html")


def index(request):
    products = models.Product.objects.all()
    # print(products)
    return render(request, "index.html", context={"products": products})


def detail(request, id: int, title: str):
    # product_detail = models.Product.objects.get(id=id)
    # try:
    #     product_detail = models.Product.objects.get(id=id)
    #     context = {"product_detail": product_detail}
    # except models.Product.DoesNotExist:
    #     raise Http404("product does not exist")

    product_detail = get_object_or_404(models.Product, id=id)
    context = {"product_detail": product_detail}
    return render(request, "detail.html", context=context)


def store(request):
    category = request.GET.get('category')
    if category is not None:
        products = models.Product.objects.filter(category__title=category)
        return render(request, "store.html", {"products": products})

    products = models.Product.objects.all()
    return render(request, "store.html", {"products": products})

@require_POST
def add_to_cart(request):
    product_id = int(request.POST.get("product_id"))
    quantity = int(request.POST.get("quantity"))
    update = True if request.POST.get("update") == '1' else False

    product = get_object_or_404(models.Product, id=product_id)

    cart = Cart(request)
    cart.add_to_cart(product_id, str(product.price), int(quantity), update)

    return redirect(reverse("shop:cart_detail"))

def cart_detail(request):
    cart = Cart(request)
    if cart:
        product_ids = cart.product_ids
        products = models.Product.objects.filter(id__in=product_ids)
        for product in products:
            cart[str(product.id)]["product"] = product

        for item in cart:
            item['total_price'] = Decimal(item['price']) * item['quantity']

        return render(request, "cart_detail.html", {"cart": cart})

    return render(request, "cart_detail.html")

def remove_from_cart(request, product_id):
    if Product.objects.filter(id=product_id).exists():
        cart = Cart(request)
        cart.remove_from_cart(str(product_id))
        return redirect(reverse("shop:cart_detail"))

    raise Http404("product doesnt exist.")

website/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse

def index(request):
    request.session['test'] = 'ali'
    print(request.session.get('test'))
    return HttpResponse("<h1>Website Index</h1>")

shop/templates/cart_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block styles %}
    <style>
        th, td {
            padding: 15px;
            text-align: center;
        }


        table a {
            text-decoration-line: underline;
        }

        .add-to-cart-btn a {
            text-decoration-line: unset ;
        }

        .add-to-cart .qty-label .input-number {
            width: 77px;
            display: inline-block;
        }

        .add-to-cart .qty-label {
            display: inline-block;
            font-weight: 500;
            font-size: 12px;
            text-transform: uppercase;
            margin-right: 15px;
            margin-bottom: 0px;
        }
    </style>
{% endblock styles %}
{% block content %}
    <h1>Cart detail</h1>
    <table>
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total Price</th>
            <th>Remove</th>
        </tr>

        {% for item in cart %}
            <tr>
                <td>
                    <img src="{{ item.product.image.url }}" alt="{{ item.product.title }}" width="100px"/>
                </td>
                <td>
                    <a href="{{ item.product.get_absolute_url }}">
                        {{ item.product.title }}
                    </a>
                </td>
                <td>{{ item.price }}</td>
                <td>
                    <div class="add-to-cart">
                        <form method="post" action="{% url 'shop:add_to_cart' %}">
                            <div class="qty-label">
                                <div class="input-number">
                                    <input type="number" name="quantity" value="{{ item.quantity }}">
                                    <input type="hidden" name="product_id" value="{{ item.product.id }}">
                                    <input type="hidden" name="update" value="1">
                                    <span class="qty-up">+</span>
                                    <span class="qty-down">-</span>
                                </div>
                            </div>

                            <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> update</button>
                            {% csrf_token %}
                        </form>

                    </div>
                </td>
                <td>{{ item.total_price }}</td>
                <td>
                    <button class="add-to-cart-btn"
                            href="{% url 'shop:remove_from_cart' product_id=item.product.id %}">
                        <a type="button" href="{% url 'shop:remove_from_cart' product_id=item.product.id %}">
                            <i class="fa fa-trash-o alert-danger"></i>
                            remove
                        </a>
                    </button>
                </td>
            </tr>
        {% endfor %}

    </table>

{% endblock content %}

shop/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Checkout {% endblock title %}

{% block content %}

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <h3 class="breadcrumb-header">Checkout</h3>
                <ul class="breadcrumb-tree">
                    <li><a href="#">Home</a></li>
                    <li class="active">Checkout</li>
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->

<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <div class="col-md-7">
                <!-- Billing Details -->
                <div class="billing-details">
                    <div class="section-title">
                        <h3 class="title">Billing address</h3>
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="first-name" placeholder="First Name">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="last-name" placeholder="Last Name">
                    </div>
                    <div class="form-group">
                        <input class="input" type="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="address" placeholder="Address">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="city" placeholder="City">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="country" placeholder="Country">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="zip-code" placeholder="ZIP Code">
                    </div>
                    <div class="form-group">
                        <input class="input" type="tel" name="tel" placeholder="Telephone">
                    </div>
                    <div class="form-group">
                        <div class="input-checkbox">
                            <input type="checkbox" id="create-account">
                            <label for="create-account">
                                <span></span>
                                Create Account?
                            </label>
                            <div class="caption">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt.</p>
                                <input class="input" type="password" name="password" placeholder="Enter Your Password">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Billing Details -->

                <!-- Shiping Details -->
                <div class="shiping-details">
                    <div class="section-title">
                        <h3 class="title">Shiping address</h3>
                    </div>
                    <div class="input-checkbox">
                        <input type="checkbox" id="shiping-address">
                        <label for="shiping-address">
                            <span></span>
                            Ship to a diffrent address?
                        </label>
                        <div class="caption">
                            <div class="form-group">
                                <input class="input" type="text" name="first-name" placeholder="First Name">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="last-name" placeholder="Last Name">
                            </div>
                            <div class="form-group">
                                <input class="input" type="email" name="email" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="address" placeholder="Address">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="city" placeholder="City">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="country" placeholder="Country">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="zip-code" placeholder="ZIP Code">
                            </div>
                            <div class="form-group">
                                <input class="input" type="tel" name="tel" placeholder="Telephone">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Shiping Details -->

                <!-- Order notes -->
                <div class="order-notes">
                    <textarea class="input" placeholder="Order Notes"></textarea>
                </div>
                <!-- /Order notes -->
            </div>

            <!-- Order Details -->
            <div class="col-md-5 order-details">
                <div class="section-title text-center">
                    <h3 class="title">Your Order</h3>
                </div>
                <div class="order-summary">
                    <div class="order-col">
                        <div><strong>PRODUCT</strong></div>
                        <div><strong>TOTAL</strong></div>
                    </div>
                    <div class="order-products">
                        <div class="order-col">
                            <div>1x Product Name Goes Here</div>
                            <div>$980.00</div>
                        </div>
                        <div class="order-col">
                            <div>2x Product Name Goes Here</div>
                            <div>$980.00</div>
                        </div>
                    </div>
                    <div class="order-col">
                        <div>Shiping</div>
                        <div><strong>FREE</strong></div>
                    </div>
                    <div class="order-col">
                        <div><strong>TOTAL</strong></div>
                        <div><strong class="order-total">$2940.00</strong></div>
                    </div>
                </div>
                <div class="payment-method">
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-1">
                        <label for="payment-1">
                            <span></span>
                            Direct Bank Transfer
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-2">
                        <label for="payment-2">
                            <span></span>
                            Cheque Payment
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-3">
                        <label for="payment-3">
                            <span></span>
                            Paypal System
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                </div>
                <div class="input-checkbox">
                    <input type="checkbox" id="terms">
                    <label for="terms">
                        <span></span>
                        I've read and accept the <a href="#">terms & conditions</a>
                    </label>
                </div>
                <a href="#" class="primary-btn order-submit">Place order</a>
            </div>
            <!-- /Order Details -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /SECTION -->

{% endblock content %}